language: python
arch:
  - amd64 
  - ppc64le
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
services:
  - memcached
install: python setup.py install
before_script: pip install -r test-requirements.txt
script:
  - if [ " $TRAVIS_CPU_ARCH" = "ppc64le" ]; then
      pytest;
    else
      flake8;
    fi
  - nosetests
  - python -c 'import memcache; memcache._doctest()'
matrix:
  exclude:
   - arch: ppc64le
     python: pypy
